// Code generated by goctl. DO NOT EDIT.
package types

type PingPeq struct {
}

type PingRes struct {
	Code int64 `json:"code"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Uid          string `json:"uid"`
	Nickname     string `json:"nickname"`
	Pic          string `json:"pic"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
}

type LogoutReq struct {
	Uid string `json:"uid"`
}

type LogoutResp struct {
	IsSuc bool `json:"is_suc"`
}

type UserInfoReq struct {
	Uid string `path:"uid"`
}

type UserinfoResp struct {
	Uid      string `json:"uid"`
	Nickname string `json:"nickname"`
	Pic      string `json:"pic"`
}
